// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/app/refsource"
)

// RefSourceMock is a mock implementation of ui.RefSource.
//
//	func TestSomethingThatUsesRefSource(t *testing.T) {
//
//		// make and configure a mocked ui.RefSource
//		mockedRefSource := &RefSourceMock{
//			BranchesFunc: func() (refsource.BranchList, error) {
//				panic("mock out the Branches method")
//			},
//			CheckRefFunc: func(ref string) error {
//				panic("mock out the CheckRef method")
//			},
//			PullRequestRefFunc: func(number int) (string, error) {
//				panic("mock out the PullRequestRef method")
//			},
//			PullRequestsFunc: func() ([]refsource.PullRequest, error) {
//				panic("mock out the PullRequests method")
//			},
//		}
//
//		// use mockedRefSource in code that requires ui.RefSource
//		// and then make assertions.
//
//	}
type RefSourceMock struct {
	// BranchesFunc mocks the Branches method.
	BranchesFunc func() (refsource.BranchList, error)

	// CheckRefFunc mocks the CheckRef method.
	CheckRefFunc func(ref string) error

	// PullRequestRefFunc mocks the PullRequestRef method.
	PullRequestRefFunc func(number int) (string, error)

	// PullRequestsFunc mocks the PullRequests method.
	PullRequestsFunc func() ([]refsource.PullRequest, error)

	// calls tracks calls to the methods.
	calls struct {
		// Branches holds details about calls to the Branches method.
		Branches []struct {
		}
		// CheckRef holds details about calls to the CheckRef method.
		CheckRef []struct {
			// Ref is the ref argument value.
			Ref string
		}
		// PullRequestRef holds details about calls to the PullRequestRef method.
		PullRequestRef []struct {
			// Number is the number argument value.
			Number int
		}
		// PullRequests holds details about calls to the PullRequests method.
		PullRequests []struct {
		}
	}
	lockBranches       sync.RWMutex
	lockCheckRef       sync.RWMutex
	lockPullRequestRef sync.RWMutex
	lockPullRequests   sync.RWMutex
}

// Branches calls BranchesFunc.
func (mock *RefSourceMock) Branches() (refsource.BranchList, error) {
	if mock.BranchesFunc == nil {
		panic("RefSourceMock.BranchesFunc: method is nil but RefSource.Branches was just called")
	}
	callInfo := struct {
	}{}
	mock.lockBranches.Lock()
	mock.calls.Branches = append(mock.calls.Branches, callInfo)
	mock.lockBranches.Unlock()
	return mock.BranchesFunc()
}

// BranchesCalls gets all the calls that were made to Branches.
// Check the length with:
//
//	len(mockedRefSource.BranchesCalls())
func (mock *RefSourceMock) BranchesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockBranches.RLock()
	calls = mock.calls.Branches
	mock.lockBranches.RUnlock()
	return calls
}

// CheckRef calls CheckRefFunc.
func (mock *RefSourceMock) CheckRef(ref string) error {
	if mock.CheckRefFunc == nil {
		panic("RefSourceMock.CheckRefFunc: method is nil but RefSource.CheckRef was just called")
	}
	callInfo := struct {
		Ref string
	}{
		Ref: ref,
	}
	mock.lockCheckRef.Lock()
	mock.calls.CheckRef = append(mock.calls.CheckRef, callInfo)
	mock.lockCheckRef.Unlock()
	return mock.CheckRefFunc(ref)
}

// CheckRefCalls gets all the calls that were made to CheckRef.
// Check the length with:
//
//	len(mockedRefSource.CheckRefCalls())
func (mock *RefSourceMock) CheckRefCalls() []struct {
	Ref string
} {
	var calls []struct {
		Ref string
	}
	mock.lockCheckRef.RLock()
	calls = mock.calls.CheckRef
	mock.lockCheckRef.RUnlock()
	return calls
}

// PullRequestRef calls PullRequestRefFunc.
func (mock *RefSourceMock) PullRequestRef(number int) (string, error) {
	if mock.PullRequestRefFunc == nil {
		panic("RefSourceMock.PullRequestRefFunc: method is nil but RefSource.PullRequestRef was just called")
	}
	callInfo := struct {
		Number int
	}{
		Number: number,
	}
	mock.lockPullRequestRef.Lock()
	mock.calls.PullRequestRef = append(mock.calls.PullRequestRef, callInfo)
	mock.lockPullRequestRef.Unlock()
	return mock.PullRequestRefFunc(number)
}

// PullRequestRefCalls gets all the calls that were made to PullRequestRef.
// Check the length with:
//
//	len(mockedRefSource.PullRequestRefCalls())
func (mock *RefSourceMock) PullRequestRefCalls() []struct {
	Number int
} {
	var calls []struct {
		Number int
	}
	mock.lockPullRequestRef.RLock()
	calls = mock.calls.PullRequestRef
	mock.lockPullRequestRef.RUnlock()
	return calls
}

// PullRequests calls PullRequestsFunc.
func (mock *RefSourceMock) PullRequests() ([]refsource.PullRequest, error) {
	if mock.PullRequestsFunc == nil {
		panic("RefSourceMock.PullRequestsFunc: method is nil but RefSource.PullRequests was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPullRequests.Lock()
	mock.calls.PullRequests = append(mock.calls.PullRequests, callInfo)
	mock.lockPullRequests.Unlock()
	return mock.PullRequestsFunc()
}

// PullRequestsCalls gets all the calls that were made to PullRequests.
// Check the length with:
//
//	len(mockedRefSource.PullRequestsCalls())
func (mock *RefSourceMock) PullRequestsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPullRequests.RLock()
	calls = mock.calls.PullRequests
	mock.lockPullRequests.RUnlock()
	return calls
}
