// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/app/session"
)

// SessionStoreMock is a mock implementation of ui.SessionStore.
//
//	func TestSomethingThatUsesSessionStore(t *testing.T) {
//
//		// make and configure a mocked ui.SessionStore
//		mockedSessionStore := &SessionStoreMock{
//			OpenFunc: func(req session.Request) (session.Opened, error) {
//				panic("mock out the Open method")
//			},
//			SaveFunc: func(s *session.Session) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedSessionStore in code that requires ui.SessionStore
//		// and then make assertions.
//
//	}
type SessionStoreMock struct {
	// OpenFunc mocks the Open method.
	OpenFunc func(req session.Request) (session.Opened, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(s *session.Session) error

	// calls tracks calls to the methods.
	calls struct {
		// Open holds details about calls to the Open method.
		Open []struct {
			// Req is the req argument value.
			Req session.Request
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// S is the s argument value.
			S *session.Session
		}
	}
	lockOpen sync.RWMutex
	lockSave sync.RWMutex
}

// Open calls OpenFunc.
func (mock *SessionStoreMock) Open(req session.Request) (session.Opened, error) {
	if mock.OpenFunc == nil {
		panic("SessionStoreMock.OpenFunc: method is nil but SessionStore.Open was just called")
	}
	callInfo := struct {
		Req session.Request
	}{
		Req: req,
	}
	mock.lockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	mock.lockOpen.Unlock()
	return mock.OpenFunc(req)
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//
//	len(mockedSessionStore.OpenCalls())
func (mock *SessionStoreMock) OpenCalls() []struct {
	Req session.Request
} {
	var calls []struct {
		Req session.Request
	}
	mock.lockOpen.RLock()
	calls = mock.calls.Open
	mock.lockOpen.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *SessionStoreMock) Save(s *session.Session) error {
	if mock.SaveFunc == nil {
		panic("SessionStoreMock.SaveFunc: method is nil but SessionStore.Save was just called")
	}
	callInfo := struct {
		S *session.Session
	}{
		S: s,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(s)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedSessionStore.SaveCalls())
func (mock *SessionStoreMock) SaveCalls() []struct {
	S *session.Session
} {
	var calls []struct {
		S *session.Session
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
